server:
  port: 9006
spring:
  application:
    name: his-careplan #服务名
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hisdb?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
jwt:
  config:
    key: zcmu
    ttl: 360000
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true
jwt:
  config:
    key: zcmu
    ttl: 360000