server:
  port: 9001
spring:
  application:
    name: his-ward #服务名
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hisdb?characterEncoding=utf-8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true